project:
  type: book

book:
  title: "garden"
  author: "Anya Ferguson"
  date: today
  chapters:
    - index.qmd
    - calendar.qmd
    - fruit-veg-herbs.qmd
    - indoor.qmd
    - outdoor.qmd
  repo-url: https://github.com/AnyaJade/garden
  repo-branch: main

execute: 
  eval: true
  echo: false
  warning: false

format:
  html:
    theme: 
      dark: darkly
      light: cosmo



