# Fruits, vegetables and herbs

## Apples {#sec-apple}

- Tree in garden
- Got 3 or 4 apples in 2024
- Left alone

## Blackcurrant sage {#sec-blackcurrant}

- Given cutting Dec 2024
- Seems to be growing indoors ok

## Bay {#sec-bay}

- Got really big tree in garden and left alone in 2024
- See how to get a successful cutting

## Carrots {#sec-carrot}

- Sow March to July
- 20cm apart
- In 2023 and 2024, ended up with very small and few carrots
- To save seed, make sure no other carrots within 500m. Crosses with carrots are easily identifiable as the thin, white root will be dominant.

## Chillies {#sec-chilli}

- Planted in 2024 and still have 3 plants, seem to be doing ok

## Chives {#sec-chives}

- Sow March - May
- Previous attempts failed, have one bought one and kept over winter - aim is to move outside

## Coriander {#sec-coriander}

- Sow indoors anytime
- When large enough to handle, thin to 20cm apart
- To harvest, take a few leaves from each plant

## Courgette {#sec-courgette}

(RHS)[https://www.rhs.org.uk/vegetables/courgettes/grow-your-ow]n

- Best started indoors, because slugs and snails
- Sow the seeds individually on their side, 13mm (½in) deep, in 7.5cm (3in) pots of moist seed compost. Then place in a heated propagator, greenhouse or on a sunny windowsill enclosed in a clear polythene bag. 
- Need 18–21°C to germinate.
- Once seedlings appear, take the pots out of the propagator or remove the bag.
- Plant out in early summer after hardening off, with general purpose fertiliser such as Vitax Q4 over the compost
- In containers at least 45cm wide or in ground spaced 90cm apart
- Thirsty plants
- Feed every 10-14 days with high potash liquid fertiliser once first fruits start to swell

## Cucumber {#sec-cucumber}

- Given a plant and grew indoors in 2024
- Biggish pot
- Got a few fruits 15cm long
- Grew tall
- Pinched out to encourage bushier

## Dill {#sec-dill}

- Sow March - May
- Do not grow near fennel

## Garlic {#sec-garlic}

- Have in past planted a clove or two and used the sprouts like chives

## Grapes {#sec-grapes}

- Vine in garden
- Got lots of bunches in 2024, but small and sour
- Left mostly alone, a little pruning / cutting back because grew a lot and everywhere
- Next time - thin grapes, so can grow bigger and hopefully sweeter?
- Leaves start to appear late April
- Beginnings of grapes appear May

## Green beans {#sec-beans}

- Sow in mid-April
- Planted 6 in raised bed in 2024
- Got lots of beans, grew very tall
- Next time - Fewer plants and bigger sticks

## Jaman {#sec-jaman}

- Gran gave a pot in autumn 2024
- Grows well in kitchen
- Makes tasty pakora
- Seems quite hardy

## Lavendar {#sec-lavendar}

- Got three plants in 2024
- The two by the door seem to be doing well, but the one in the pot needs more watering

## Lemon Mint {#sec-lemon-mint}

- Found in garden in 2024
- Moved to a pot and seems to be doing fine

## Lettuce {#sec-lettuce}

- Sow March to July
- 20cm apart
- Most seeds germinate

## Mint {#sec-mint}

- Sow Feb - May

## Mustard {#sec-mustard}

- Can be sown throughout the summer and into autumn for an early winter crop. 
- It will withstand some cold but will be killed off by a hard frost. 
- Spacing of 50cm.

## Oregano {#sec-oregano}

- Bush in garden 2024
- Mostly left alone and seems fine

## Parsley {#sec-parsley}

- Put one in a pot outside in 2024, seems fine

## Pear {#sec-pear}

- Tree in garden
- Left alone in 2024 and got 2 pears

## Peppers {#sec-pepper}

(RHS)[https://www.rhs.org.uk/vegetables/peppers/grow-your-own]

- Sow indoors in mid Feb or early March
- Need 18-21 degrees to germinate
- Once seedlings appear, keep at 16-18 degrees in bright light and water regularly
- When they have two true leaves, move into own 7.5-9cm pot
- Plant into final container in mid-May in an unheated greenhouse, at least 30cm wide
- Feed once a week with high-potassium liquid fertiliser once flowering starts
- Keep soil evenly moist
- When reach about 30cm tall, pinch main stem(s)
- Harvest mid-summer into autumn

## Plums {#sec-plum}

- Tree in garden
- Got none in 2024
- Left alone

## Potatoes {#sec-potato}

- Threw a sprouting potato in a black bag in summer 2024 and worked well
- Emptied bag out once flowered / leaves started to turn and got lots of small ones

## Raspberries {#sec-raspberry}

- Loads canes came up in 2024
- Left alone and got a few handfuls of raspberries
- Cut some dead canes back in winter, see what happens in 2025
- Started to leaf in March

## Rocket {#sec-rocket}

- Sow March to July
- 20cm apart

## Rosemary {#sec-rosemary}

- Big bush in garden 2024, left alone
- Maybe prune back so others can grow?

## Runner bean {#sec-runner}

- Is perennial if the roots are lifted and stored like dahlias, but treated as an annual as the plants grow so quickly.
- Sow seeds in mid-May and plant out hardened-off plants after the last frost.
- Allow at least 15cm between rows. 
- Harvest pods before they are over-mature to avoid stringiness, and pick frequently to encourage more to form. 
- Leave some on the plant to mature if you wish to save the seed. 
- Runner beans readily cross-pollinate and need at least 1000m between varieties.

## Sage {#sec-sage}

- Sow March-May
- Kept some small plants over winter, but see how they do / plant more and move outside

## Spinach {#sec-spinach}

- Sowed some in 2024, but did not use

## Spring onions {#sec-spring-onion}

## Strawberries {#sec-strawberry}

- Got a black bag in 2023
- Left alone in 2024 and got a few strawberries
- See how can get more and how to propogate

## Squash {#sec-squash}

- Sow Apr-May - warm and danger of frost has passed
- Sow at least 3 seeds to ensure that if one plant is mainly producing male flowers, there is a higher probability that there will be a female flower on another for pollination. 
- Allow lots of space (1-1.5m, more for trailing types).
- Pollination is required for good fruit set, and can be done by hand if insects are scarce. 
- For winter squash, don't allow too many fruits since need time/resources to develop.
- Summer squash can be allowed to produce lots of fruit and harvested when ready (it should still be possible to penetrate the skin with a thumbnail).
- Harvest winter squash when the vines have been cut down by frost. Allow the fruits to ripen further in the sun for several weeks after harvest for maximum storage time.

## Tomatoes {#sec-tomato}

- Sow late Feb - Mar, 15-20 degrees
- Transplant when large enough to handle
- Plant out in 30cm pots
- Feed once flowers form
- Had three plants and got less than 20 tomatoes in 2024, but didn't feed them and maybe didn't water them enough?

## Thyme {#sec-thyme}

- Sow indoors Feb - May
- When large enough to handle move into individual pots
- In May - July plant outside
- Cut off flowering shoots for best flavour