# Outdoor plants

## Acorus gramineus 'Variegatus' variegated dwarf rush {#sec-acorus}

## Ajuga {#sec-ajuga}

## Bluebells {#sec-bluebell}

- Start to sprout in Feb
- Flowers March-April

## Broad-leafed Dock {#sec-dock}

## Buddleja {#sec-buddleja}

- Should cut back in autumn

## Campion {#sec-campion}

## Clematis {#sec-clematis}

- Flowers late April to May

## Cowslip {#sec-cowslip}

- Flowers late April to early May

## Crocosmia {#sec-crocosmia}

## Daffodils {#sec-daffodil}

- Appear late February, flowering through March
- Lift and divide in autumn

## Dahlia {#sec-dahlia}

- Lift and divide once leaves start to blacken and before frosts
- Clean and leave in dry, cool/warm place - storage cupboard is ideal
- Plant once no more frost, late March/April

## Dianthus plumaris {#sec-dianthus}

## Forget-me-nots {#sec-forget}

- Flowers in April

## Foxglove {#sec-foxglove}

## Geranium Maculatum {#sec-geranium_m}

## Geranium Cranesbill {#sec-geranium_c}

- Flowers late April to early May

## Ground Elder {#sec-elder}

## Hellebore {#sec-hellebore}

- Lift and divide after flowering
- Flowers Jan - early April

## Honeysuckle {#sec-honeysuckle}

## Hops {#sec-hops}

- Appears late April

## Japenese quince {#sec-quince}

- Flowers in April

## Lobelia {#sec-lobelia}

(RHS)[https://www.rhs.org.uk/plants/142728/lobelia-erinus/details]

- Sow seeds in late winter at 13-18 degrees
- Grow in deep, fertile, reliably moist soil in full sun or partial shade. 
- Apply a balanced fertilizer every two weeks during spring and early summer and a nitrogen-free fertilizer every two weeks from mid-summer onwards
- No pruning required

## Orpine {#sec-orpine}

- Stonecrop
- Start to grow again early March

## Peonies {#sec-peony}

- Start to grow again early March
- Flowers in May
- Propagate late summer

## Red-flowering currant {#sec-currant}

- Start to grow again early March
- Flowers March - April

## Red valerian {#sec-valerian}

- Flowers May

## Roses {#sec-rose}

- Starts to bud in May

## Rudbeckia {#sec-rudbeckia}

## Snapdragon {#sec-snapdragon}

- Flowers in May

## Snowdrops {#sec-snowdrop}

- Come up in Jan
- Can lift and divide bulbs after flowering, end of March

## Stevia {#sec-stevia}

## Summer snowflake, Gratiola officinalis {#sec-snowflake} 

- Flowers in April

## Sunflower {#sec-sunflower}

## Lathyrus Odaratus {#sec-sweetpea}

- Sweet pea 
- Collect seeds once pods have gone papery brown
- Dry pods out until splits, then dry seeds out and pack away
- Soak 24 hours in warm water before sowing in Feb
- Plant out late April

## Tutsan {#sec-tutsan}

## Water starwort {#sec-starwort}


